### PR TITLE
Correctly classify devDependencies as dependencies

### PR DESCRIPTION
**Pull request by natashaarmbrust**
Some of the `devDependencies` listed should be `dependencies` instead per info here (https://docs.npmjs.com/specifying-dependencies-and-devdependencies-in-a-package-json-file)

### CODE REVIEW

**Comment by natashaarmbrust** [comment]
@junkboy0315 can you take a look when you get a chance? Would love to merge this in and cut a new release :).

**Comment by junkboy0315** [comment]
Hi @natashaarmbrust , thanks for PR.

I'm not quite familiar about npm dependencies things though, but in my understanding, `dependencies` packages are packages that installed in the production environment for the **users of this package** (= Comsumer of the `react-compare-image`). 

So, I think they don't need these packages (they only need `dist/bundle.js` which is specified `package.json`'s `main` part). Am I wrong?

**Comment by natashaarmbrust** [comment]
@junkboy0315 Anything in `dependencies` is what needs to be available in production at runtime. Since your code calls react, react-dom, etc. so those should be classified as dependencies because your code calls them at runtime. If you were only using the types from react that would make it a dev dependency because types are needed at compile time only, not runtime.

**Comment by junkboy0315** [comment]
`react` and `react-dom` must be listed in the `peerDependencies` as they are already listed.

https://prateeksurana.me/blog/react-library-with-typescript/#adding-react

And this library doesn't have any other dependencies at runtime.

**Pull request closed without merging**
