### PR TITLE
feat: add react 18 support

### PR DESCRIPTION
**Pull request by damjtoh**
Bumps react versions in `peerDependencies`.,

### CODE REVIEW

**Comment by naajil-aamir** [comment]
Any clue when this Pull request will be merged?

**Comment by bkibbeyWork** [comment]
It looks like this one is ready to go... is there a technical reason it is delayed? @junkboy0315

**Comment by naajil-aamir** [comment]
> It looks like this one is ready to go... is there a technical reason it is delayed? @junkboy0315

You can search for "react-compare-image-r18". It's the same library, just with react 18 added as dependencies. That's what I ended up doing

**Comment by junkboy0315** [comment]
sorry for delay, published as v3.3.0.
confirmed it works with React 18 without problems.

**Pull request merged**
