### PR TITLE
Add custom handle feature to V1

### PR DESCRIPTION
**Pull request by janedotbiz**
Was using `react-compare-image` on a project where I needed the ability to add custom handle: a button with a hover effect—one that wouldn't block pointer events for the image comparison. 

(My first approach to getting a custom handle, used the callback function to position the handle as needed, but it was either blocking interactions with `ReactImageCompare`, or when `pointer-events: none` was applied, wasn't getting any `:hover` styling.)

Thought others might need this as well. 

Commit 171cf25 addresses some warnings my linter threw.

### CODE REVIEW

**Comment by junkboy0315** [comment]
Hi @janedotbiz !
I will try this PR ASAP. Give me some time.  Thanks a lot!!

**Comment by daigof** [comment]
Please implement this feature, I need to get rid of the handle and have a plain 2px bar

**Comment by janedotbiz** [comment]
@daigof You can set the `handleSize` to `0` and effectively get rid of/hide the handle that way.

**Comment by junkboy0315** [comment]
merged and published as v1.2.0. thanks @janedotbiz !

@daigof 
Hi, you can set empty handle from now on.

```jsx
<ReactCompareImage
  handle={<React.Fragment />}
/>
```

**Comment by daigof** [comment]
thank you so much guys. Awesome.

**Pull request merged**
