### PR TITLE
add container props

### LINKED ISSUE #22: Can I make override container style?
Hi! Help me, please. Can I make override container style in div with data-testid="container"?

```
<div
        style={{
          ...styles.container,
          display: allImagesLoaded ? 'block' : 'none',
        }}
        ref={containerRef}
        data-testid="container"
      > 
      ...
</div>
```

### PR DESCRIPTION
**Pull request by Torbochka**
close #22

### CODE REVIEW

**Comment by junkboy0315** [comment]
Hi, how about to apply css to its parent?

```jsx
<div style={{anyCSS: youLike}}>
  <ReactCompareImage />
</div>
```

I can't image usecases where the container style must be changed directly.
What do you think?

**Comment by junkboy0315** [comment]
Hi, @Torbochka 
How about to apply css to its parent?

```jsx
<div style={{anyCSS: youLike}}>
  <ReactCompareImage />
</div>
```

I can't image usecases where the container style must be changed directly.
What do you think?

**Comment by Torbochka** [comment]
Hi, @junkboy0315 

> How about to apply css to its parent?

This solution good work for me. I think pr can close). Thanks

**Comment by junkboy0315** [comment]
@Torbochka 
I'm glad to hear that. Anyway, thank you for sending PR!

**Pull request closed without merging**
